version: "3"
services:
  nightbot-service:
    container_name: nightbot-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    # environment:
    #   - PORT=5000
    #   - NODE_ENV=development
    # volumes:
    #   - .:/app
    # command: npm run dev
